<?php
namespace Budgetlens\BolRetailerApi\Types;

class ReturnResultTypes
{
    const RETURN_RECEIVED = "RETURN_RECEIVED";
    const EXCHANGE_PRODUCT = "EXCHANGE_PRODUCT";
    const RETURN_DOES_NOT_MEET_CONDITIONS = "RETURN_DOES_NOT_MEET_CONDITIONS";
    const REPAIR_PRODUCT = "REPAIR_PRODUCT";
    const CUSTOMER_KEEPS_PRODUCT_PAID = "CUSTOMER_KEEPS_PRODUCT_PAID";
}
